#开发环境
breakpoint:
  upload:
    dir: D:/data0/uploads/
    #1024*1024=1 048 576,5M=5 242 880
    chunkSize: 5 242 880

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 30
      max-idle: 10
      max-wait: 10000
    timeout: 5000
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://localhost:3306/test
    data-username: root
    data-password: Neuro@2601
    driver-class-name: com.mysql.jdbc.Driver
